spring:
  sendgrid:
    api-key: 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
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-1.cuhciktf07oe.us-east-1.rds.amazonaws.com/frontedge

    username: admin
    password: 117028Nur

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 5005

